//
// Created by Advik on 27-10-2023.
//

#ifndef HELLOIMGUI_EXIT_CODES_H
#define HELLOIMGUI_EXIT_CODES_H

int SUCCESS = 1;
int GLFW_INIT_FAIL = -1;
int GLFW_WINDOW_CREATION_FAIL = -2;
int GLFW_SHAPE_CREATION_FAIL = -3;
int GLAD_INIT_FAIL = -4;
int SHADER_COMPILATION_FAIL = -5;
int SHADER_LINKING_FAIL = -6;
int SHADER_NOT_FOUND = -7;


#endif //HELLOIMGUI_EXIT_CODES_H
